### PR TITLE
Try using MRCPP conda package

### PR DESCRIPTION
**Pull request by robertodr**

### CODE REVIEW

**Comment by robertodr** [comment]
This is ready. However, one Travis build fails with a segfault (dammit!) and I cannot reproduce it (even more dammit!)

**Comment by robertodr** [comment]
I can confirm that there's some weirdness going on with release builds of the MRCPP package that only show up when using it with  VAMPyR.

**Comment by stigrj** [comment]
I get a redefinition warning for `PROGRAM_VERSION` and `GIT_REVISION` in mrchem if I build mrcpp and mrchem separately. Not sure if this was introduced with this PR, or whether it should be considered mrcpp's or mrchem's problem?

**Comment by robertodr** [comment]
I've seen this happen when @Gabrielgerez compiles his branch and he's not using the conda package. We meant to open an issue, but forgot.

**Comment by robertodr** [comment]
I've updated the package (now it's made right from `master` of MRCPP) but testing still fails. I'll wait until #32 is in to continue debugging.

**Comment by robertodr** [comment]
Superseded by #33. Closing

**Pull request closed without merging**
