### PR TITLE
Restart work on using the MRCPP conda package

### PR DESCRIPTION
**Pull request by robertodr**
Let's see...

### CODE REVIEW

**Comment by robertodr** [comment]
The package is outdated :facepalm:

**Comment by robertodr** [comment]
Tests for the release build linked to serial MRCPP segfault.

**Comment by robertodr** [comment]
Even with the new conda package, the test still segfaults. I suspect some weird interaction with pybind11...

**Comment by robertodr** [comment]
It only took a year to get this done :smile_cat:

**Review by stigrj — APPROVED** [review]
:partying_face:

**Pull request merged**
