### PR TITLE
Fix python detection for pyenv

### PR DESCRIPTION
**Pull request by bjorgve**

### CODE REVIEW

**Comment by stigrj** [comment]
There seems to be some ambiguity about the Python version on Travis

**Comment by bjorgve** [comment]
Yes it looks like it requires python 3.6, for no particular reason as far as I can see. Do you see why @robertodr?

**Comment by robertodr** [comment]
I'll look into it. I think we need to purge the Travis python environment.

**Comment by bjorgve** [comment]
Possibly an issue here: At least on my computer the library file, vampyr3d, that ends up in the build/lib directory lacks the .so extension. Things work if it is renamed to vampyr3d.so.

**Comment by robertodr** [comment]
Didn't we test that the hack was working on your laptop?

**Comment by bjorgve** [comment]
Think we only checked if it built.

**Comment by robertodr** [comment]
Dang :( OK, probably we (I?) need to rewrite the `pybind11_add_module` macro after all...

**Comment by bjorgve** [comment]
Sounds fun! :D

**Comment by robertodr** [comment]
no-fun-not-ever

**Pull request closed without merging**
