### PR TITLE
Fix bindings for Gaussian inheritance hierarchy

### PR DESCRIPTION
**Pull request by robertodr**
This follows advice given here: https://github.com/pybind/pybind11/issues/2064#issuecomment-691535995 and requires to remove the `final` qualifier from `GaussFunc` and `GaussPoly` in MRCPP to work properly.

### CODE REVIEW

**Comment by robertodr** [comment]
Note that CI for this will fail until the changes in MRChemSoft/MRCPP#154 are in and a new conda package is built.

**Comment by stigrj** [comment]
`MRCPP-v1.3.5` out

**Comment by robertodr** [comment]
I've updated the PR so that it fetched v1.3.5 The conda-forge bot should notify us soon of an update to the recipe and the package.

**Comment by robertodr** [comment]
Uhm, didn't work as expected... I'll have to check later.

**Comment by robertodr** [comment]
So, it works if I build against the conda package, but spits some horrible compiler errors if I download MRCPP and build it on-the-fly :man_shrugging:

**Comment by stigrj** [comment]
so, is this good or not?

**Comment by robertodr** [comment]
Locally, I only get warnings, not errors, when compiling MRCPP on the fly. I'm trying to figure out how to fix those, but that will be in another PR.

**Review by stigrj — APPROVED** [review]

**Pull request merged**
