### PR TITLE
Update multiply

### PR DESCRIPTION
**Pull request by bjorgve**
Making vampyr work with current master of mrcpp

### CODE REVIEW

**Comment by bjorgve** [comment]
I'm not sure why the CIs are failing. Everything works smoothly on Woolf. Do you know whats wrong @robertodr?

**Comment by stigrj** [comment]
We recently had to update the `.travis.yml` config in mrchem, looks like the same issue. Circle is complaining about a public key in the clone, don't know what that is about.

**Comment by robertodr** [comment]
You might also want to update the version of MRCPP that is fetched (look in`external/CMakeLists.txt`)

**Comment by bjorgve** [comment]
If I'm not wrong it looks like it fetches `mrcpp/master`.

**Comment by robertodr** [comment]
Indeed!

**Comment by bjorgve** [comment]
@stigrj I don't see anything different between `mrchem/travis.yml` and `vampyr/travis.yml` (apart from `sudo: false`). Which PR are you thinking about?

**Comment by robertodr** [comment]
It's on MRChem's `master` branch: https://github.com/MRChemSoft/mrchem/blob/master/.travis.yml

**Comment by robertodr** [comment]
Not sure what's wrong with CircleCI here... Something about access to the repo, even thought it downloads anonymously...

**Comment by robertodr** [comment]
I've updated the Docker image, so you should now use: `- image: quay.io/metamr/circleci_ubuntu-18.04-conda:41efbc8` in `config.yml` However, this doesn't fix the problem either, maybe @stigrj needs to reauthorize CircleCI or something...
`

**Comment by stigrj** [comment]
I can reproduce the aborted child error from Travis in debug

**Comment by stigrj** [comment]
I get the same abortion with `master` using mrcpp-1.2.0 in debug, so it's probably not related to this PR

**Comment by stigrj** [comment]
Should vampyr always point to `master`, or should we pin it to versions?

**Comment by stigrj** [comment]
I get `double free or corruption` errors for the `Eigen::MatrixXd`s in `ScalingBasis` when compiled in debug through vampyr. If I make them pointers and let them leak, then the tests pass.

**Comment by robertodr** [comment]
I'd say we should pin the dependency. I'll try running through the debugger later to see what's going on with the double free skullduggery...

**Comment by robertodr** [comment]
The debugger did not provide illumination. I've compiled on `sandel` and the `double free` occurs when doing `phi_tree = vp.vampyr3d.FunctionTree(MRA)` It could be the binding is not 100% correct when it comes to inheritance... I'm looking into it, but I'm not sure I can fix it quickly.

**Comment by stigrj** [comment]
I narrowed it down to a single line in the simplest case
```
basis = vp.InterpolatingBasis(5)
```
So just initialization and destruction of a `ScalingBasis`, in particular one of its three `Eigen::MatrixXd` members.

**Comment by robertodr** [comment]
Hmmm I removed the destructor in the base class in MRCPP and that python
line doesn't fail for me.

**Comment by stigrj** [comment]
So there was a missing `-march=native` flag. I'm deja vu-ing

**Comment by robertodr** [comment]
The agony! That flag should be exported as part of the MRCPP target then. Or removed altogether?

**Comment by robertodr** [comment]
Can you make codecov happy?

**Comment by robertodr** [comment]
FYI, MRChemSoft/mrcpp#147 does the export of the flag with the target.

**Review by robertodr — APPROVED** [review]
What a trip this "simple" change was :smile_cat:  I'll push some other changes to the bindings as follow-up.

**Comment by robertodr** [comment]
Now that all bots are happy, we can happily merge. Thanks @bjorgve!

**Comment by bjorgve** [comment]
Wow you guys did allot of work here! Thanks!

**Pull request merged**
