### PR TITLE
All dimensions are belong to us

### PR DESCRIPTION
**Pull request by robertodr**
Addresses #26 
- [X] Upgrade minimum required version of CMake to 3.14 (needed for creating symlinks)
- [X] Bind 1D and 2D
- [ ] Split up tests one per file. 

~#### Notes to self
- `apply`, `dot`, `power` and so on depend on `D` but should be exported in the main module, not the `vampyrDd` submodules.
- Some classes inherit from others in MRCPP, but only for certain dimensionalities. We now use a "phantom" type trick that could be not entirely correct. **Update** when binding D=1 and D=2, the "phantom trick" prevents the module from being loaded. Pybind11 registers the "phantoms" as the actual types. We need to figure out something else.~

### CODE REVIEW

**Comment by robertodr** [comment]
Still stuck on getting the inheritance hierarchies right for all dimensions and objects :angry: . Stay tuned...

**Comment by robertodr** [comment]
I think it's fully working now, but there are some things that I did that I do not understand, especially when comparing with the pybind11 documentation (see here pybind11/pybind11#2064) I also think that the inheritance hierarchies in MRCPP when it comes to functions are confusing and should be rethought/redone.

**Comment by bjorgve** [comment]
Travis appears to work now

**Comment by robertodr** [comment]
CI is green. Codecov is red, but I guess that's because the number of files changed.

**Comment by robertodr** [comment]
I'll have another look at using the conda package.

**Pull request merged**
