### PR TITLE
Simplify CMake

### PR DESCRIPTION
**Pull request by robertodr**
Some simplification in the CMake set up:

- Use `FetchContent` to fetch MRCPP. This means that MRCPP is not a Git submodule any longer :confetti_ball: 
- Use `pybind11_add_module` function provided by pybind11
- Enable LTO (link-time optimization) for the compiled module

I have also copied the official `.clang-format` over and reformatted the code.

### CODE REVIEW

**Comment by robertodr** [comment]
Someone with privileges should give a kick to CircleCI.

**Comment by bjorgve** [comment]
That someone is unfortunately not me. @stigrj

**Comment by robertodr** [comment]
It actually was  a problem withe the set up (wrong Docker image)

**Comment by stigrj** [comment]
Good riddance on the submodule!

**Comment by robertodr** [comment]
MRChem's turn tomorrow, I hope...

**Pull request merged**
