### PR TITLE
Bump VERSION

### PR DESCRIPTION
**Pull request by robertodr**

### CODE REVIEW

**Comment by stigrj** [comment]
This will create a tag `v0.2.0` on `master` after merge? In the MRChem model all tags live on `release/X.Y` branches.

**Comment by stigrj** [comment]
Ah, I see now :slightly_smiling_face:

**Comment by robertodr** [comment]
> This will create a tag `v0.2.0` on `master` after merge? In the MRChem model all tags live on `release/X.Y` branches.

It should not, the rule for the action is `if: contains(github.ref, 'refs/head/release')`

**Comment by stigrj** [comment]
I think you should put a `-alpha` on the version to indicate it's experimental

**Comment by robertodr** [comment]
So `0.2.0a0`? I'm following Python naming conventions, since this will be a Python package: https://www.python.org/dev/peps/pep-0440/

**Comment by stigrj** [comment]
How does Python label the `latest` development version which is not an official release? In my opinion it should not be the same as the next actual release

**Comment by robertodr** [comment]
I see what you mean now. I don't think there's anything to that effect in the document I linked. Those versioning numbers are for _released_ packages. I'll do `0.2.0-unreleased` then, I think it's clearer than calling it alpha or whatever, as it's never going to be tagged.

**Review by stigrj — APPROVED** [review]
:ok_hand:

**Pull request merged**
